.TH "set_once::DataNotSetException" 3Version 2.0.0" "SetOnce" \" -*- nroff -*-
.ad l
.nh
.SH NAME
set_once::DataNotSetException \- This class is used to throw excetion stating data nas not been set for the \fBSetOnce\fP object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SetOnce\&.hxx>\fP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const char * \fBwhat\fP () const override"
.br
.RI "returns the human readable exception in string format "
.in -1c
.SH "Detailed Description"
.PP 
This class is used to throw excetion stating data nas not been set for the \fBSetOnce\fP object\&. 
.SH "Member Function Documentation"
.PP 
.SS "const char * set_once::DataNotSetException::what () const\fC [inline]\fP, \fC [override]\fP"

.PP
returns the human readable exception in string format 
.PP
\fBReturns\fP
.RS 4
Returns the exception in const char * format 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SetOnce from the source code\&.
