.TH "C:/Users/IshaanKarnik/source/repos/SetOnce/SetOnce/SetOnce.hxx" 3Version 2.0.0" "SetOnce" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/IshaanKarnik/source/repos/SetOnce/SetOnce/SetOnce.hxx \- This file contains all required definations and implementation for the SetOnce library\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <mutex>\fP
.br
\fC#include <atomic>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBset_once::DataNotSetException\fP"
.br
.RI "This class is used to throw excetion stating data nas not been set for the \fBSetOnce\fP object\&. "
.ti -1c
.RI "class \fBset_once::SetOnce< T >\fP"
.br
.RI "This class allows teh object to be initialized only once but can be read any number of times\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file contains all required definations and implementation for the SetOnce library\&. 


.PP
\fBAuthor\fP
.RS 4
Ishaan Karnik 
.RE
.PP
\fBDate\fP
.RS 4
20-08-2023 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for SetOnce from the source code\&.
